//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public Complain()
        {
            this.UserVotesSet = new HashSet<UserVotesSet>();
            this.ComplainAction = new HashSet<ComplainAction>();
        }
    
        public int ComplainID { get; set; }
        public int ComplainCategory { get; set; }
        public string ComplainCategoryValue { get; set; }
        public string UploadFilePath { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string UserContactNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<UserVotesSet> UserVotesSet { get; set; }
        public virtual ICollection<ComplainAction> ComplainAction { get; set; }
    }
}
