//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GHCReportItEntities : DbContext
    {
        public GHCReportItEntities()
            : base("name=GHCReportItEntities")
        {
        }

        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Complain> Complain { get; set; }
        public DbSet<ComplainAction> ComplainAction { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<UserVotesSet> UserVotesSet { get; set; }
    }
}
