//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVotesSet
    {
        public int UserVoteID { get; set; }
        public int ComplainID { get; set; }
        public int UserID { get; set; }
        public int Complain_ComplainID { get; set; }
        public int UserInfo_UserID { get; set; }
    
        public virtual Complain Complain { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
